### ISSUE TITLE
Something about yara rule

### ISSUE THREAD

**Issue by liankong233** [roadwy/DefenderYara#1]
1.I think his yara condition should be `all of them`, because I tried to find a sample based on some of his names, and after comparison, I found that the rules it listed are all reflected in the sample.

2.
Some other better suggestions. Because I found that some of his type names contain definitions similar to PE and ELF, I believe his meaning should be to distinguish the types of files. So, you can try assuming some conditions.

For example, adding the condition of `uint16 (0)==0x5a4d and uint32be (uint32 (0x3c))==0x50450000` to this type of `SIGNATURE_TYPE_PEHSTR`,used to distinguish PE files.
Of course, ELF files can also be like this.

Thank you for your project.

**Comment by roadwy** [comment]
1.You are right, the condition may be is wrong, as the readme.md 

> all of condition are "any of ($a_*)", it's worng. if someone know how to get corret yara condition, PR is welcome.
if you want get correct condition, you can ref https://github.com/hillu/yara-rules-re. mybe you need analyze defender 

2. at the next commit i will add this condition.
> For example, adding the condition of uint16 (0)==0x5a4d and uint32be (uint32 (0x3c))==0x50450000 to this type of SIGNATURE_TYPE_PEHSTR,used to distinguish PE files.
- SIGNATURE_TYPE_PEHSTR_EXT
- SIGNATURE_TYPE_PEHSTR_EXT
- SIGNATURE_TYPE_ELFHSTR_EXT
