### ISSUE TITLE
[0-00} Is not effective at and will cause error at YARA-X  from this file Trojan_Win32_Singu_A.yar

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [roadwy/DefenderYara#2]
https://github.com/roadwy/DefenderYara/blob/9bbdb7f9fd3513ce30aa69cd1d88830e3cf596ca/Trojan/Win32/Singu/Trojan_Win32_Singu_A.yar#L7 Remove [0-00] from there.

**Comment by roadwy** [comment]
warning: This repo is not production-ready. and not for YARA-X，you can use raw yara.

**Comment by HydraDragonAntivirus** [comment]
Some rules are empty also
